version: '3.3'
services:
    arkserver:
        container_name: ${INSTANCE_NAME}
        stdin_open: true
        tty: true
        image: scottyhardy/docker-wine
        command: start.sh
#        user: 1010:1010
        volumes:
            - ../proton:/proton
            - ../server:/server
            - ../steamcmd:/steamcmd
            - ./start.sh:/usr/bin/start.sh
            - ./saves:/server/ShooterGame/Saved/SavedArks
            - ./config:/server/ShooterGame/Saved/Config/WindowsServer
        expose:
            - ${PORT}
            - ${QUERY_PORT}
        network_mode: host
